image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches: { only: [ master ] }

build: off  # будем использовать свой скрипт сборки

install:
  - chmod +x gradlew
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-replan-delivery.jar &

build_script:
  - chmod +x gradlew
  - ./gradlew test -Dselenide.headless=true --info  # запускаем тест, флаг --info позволяет выводить больше информации